name: Publish to Conda

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  conda-build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults
          channel-priority: strict
          
      - name: Install conda-build and anaconda-client
        shell: bash -l {0}
        run: |
          conda install conda-build anaconda-client
          
      - name: Create conda recipe directory
        shell: bash -l {0}
        run: |
          mkdir -p conda-recipe
          
      - name: Create meta.yaml
        shell: bash -l {0}
        run: |
          cat > conda-recipe/meta.yaml << 'EOF'
          {% set data = load_setup_py_data() %}
          
          package:
            name: epiinfo
            version: {{ data.get('version') }}
          
          source:
            path: ..
          
          build:
            number: 0
            script: python -m pip install . -vv
            noarch: python
          
          requirements:
            host:
              - python >=3.10
              - pip
              - setuptools
              - wheel
            run:
              - python >=3.10
              - scipy
              - ijson
              - pycryptodome
          
          test:
            imports:
              - epiinfo
              - epiinfo.Frequencies
              - epiinfo.Means
              - epiinfo.TablesAnalysis
          
          about:
            home: https://github.com/Epi-Info/epiinfo
            license: Apache-2.0
            license_file: LICENSE
            summary: 'Epi Info: Import and analyze data'
            description: |
              A Python package for epidemiological data analysis and statistical computations.
            doc_url: https://github.com/Epi-Info/epiinfo
            dev_url: https://github.com/Epi-Info/epiinfo
          
          extra:
            recipe-maintainers:
              - johncopeland
          EOF
          
      - name: Build conda package
        shell: bash -l {0}
        run: |
          conda-build conda-recipe --python ${{ matrix.python-version }}
          
      - name: Upload to Anaconda.org
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          if [ -n "$ANACONDA_API_TOKEN" ]; then
            anaconda -t $ANACONDA_API_TOKEN upload --force $(conda-build conda-recipe --python ${{ matrix.python-version }} --output)
          else
            echo "ANACONDA_TOKEN not set, skipping upload"
          fi
